- name: Create ArgoCD namespace
  command: kubectl create namespace argocd
  ignore_errors: yes

- name: Install ArgoCD
  command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  args:
    creates: /tmp/argocd.installed

- name: Touch install file to mark ArgoCD setup complete
  file:
    path: /tmp/argocd.installed
    state: touch
